apiVersion: v1
kind: Service
metadata:
  name: aks-app02
  namespace: sample-app-namespace-1742888334253
  labels:
    app.kubernetes.io/name: aks-app02
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: aks-app02
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000